### ISSUE TITLE
non existing items in /government return 303, 200

### ISSUE THREAD

**Issue by joelanman** [alphagov/content-store#324]
If you make a request for a non existing item in /government, for example:

https://www.gov.uk/api/content/government/this-does-not-exist

This returns a 303 (see other) to

https://www.gov.uk/api/content/government

which is a 200 (found) response.

I would expect a 404 (not found) on the original response

In addition, /government itself is not a valid content item, so this 200 response is confusing.

**Comment by tijmenb** [comment]
This is the correct behaviour. 

- The content store also responds to requests for prefix routes, so that pages like https://www.gov.uk/disabled-students-allowances-dsas/how-to-claim can access their "parent" content item (https://www.gov.uk/disabled-students-allowances-dsas). See https://github.com/alphagov/content-store/pull/269.
- `/government` is a valid content item, albeit one that doesn't have a HTML representation on the site.

**Comment by joelanman** [comment]
but in this example the item does not exist at all, it's nothing to do with parent items? returning a 303 and then 200 for a non existent item is really not expected behaviour

**Comment by cbaines** [comment]
> but in this example the item does not exist at all, it's nothing to do with parent items? returning a 303 and then 200 for a non existent item is really not expected behaviour

When you make a request to the content store, it finds the appropriate item to return by looking at the routes.

For the /government content item, the routes are as follows:

```
irb(main):003:0> ContentItem.find_by(_id: '/government').routes
=> [{"path"=>"/government", "type"=>"prefix"}]
```

So this content item is applicable for any path under and including `/government`, if no more specific route exists.

This is a special route, the purpose of which is to send all requests that are not handled by other frontend apps through to Whitehall. The odd thing here is that Whitehall doesn't use the content store to render responses.
